---
# tasks file for lighthouse-role
  tasks:
    - name: Install nginx
      become: true
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true
      notify: restart nginx service
  pre_tasks:
    - name: Install unzip
      become: true
      ansible.builtin.apt:
        name: unzip
        state: present
        update_cache: true
  tasks:
    - name: Get lighthouse distrib
      ansible.builtin.get_url:
        url: "https://github.com/VKCOM/lighthouse/archive/refs/heads/master.zip"
        dest: "./lighthouse.zip"
        mode: "0644"
    - name: Unarchive lighthouse distrib into nginx
      become: true
      ansible.builtin.unarchive:
        src: ./lighthouse.zip
        dest: /var/www/html/
        remote_src: true
      notify: restart nginx service
    - name: Make nginx config
      become: true
      ansible.builtin.template:
        src: /home/kali/lesson/devops-netology/08-ansible-03-yandex/templates/default.j2
        dest: /etc/nginx/sites-enabled/default
        mode: "0644"
      notify: restart nginx service
    - name: Remove lighthouse distrib
      ansible.builtin.file:
        path: "./lighthouse.zip"
        state: absent
